---
title: "Rworksheet_Mabalina#4a"
author: "Kristian B. Mabalina"
date: "2024-10-23"
output:
  pdf_document: default
  html_document: default
---
#1
```{r}
# a
shoe_size <- c(8, 9, 10, 6, 7)
height <- c(170, 180, 175, 160, 165)
gender <- c("M", "M", "M", "F", "F")

data <- data.frame(ShoeSize = shoe_size, Height = height, Gender = gender)
print(data)
```
```{r}
# b
male_data <- subset(data, Gender == "M")
female_data <- subset(data, Gender == "F")

print(male_data)
print(female_data)
```
```{r}
# c
mean_shoe_size <- mean(data$ShoeSize)
mean_height <- mean(data$Height)

print(paste("Mean Shoe Size:", mean_shoe_size))
print(paste("Mean Height:", mean_height))
```
```{r}
# d
plot(data$ShoeSize, data$Height, main="Shoe Size vs Height", xlab="Shoe Size", ylab="Height")
```
#2
```{r}
months_vector <- c("March", "April", "January", "November", "January", "September", "October", 
                   "September", "November", "August", "January", "November", "November", 
                   "February", "May", "August", "July", "December", "August", "August", 
                   "September", "November", "February", "April")


factor_months_vector <- factor(months_vector)
print(factor_months_vector)
```
#3
```{r}
direction <- c("East", "West", "North", "West", "North")
frequency <- c(1, 4, 3, 2, 1)

factor_direction <- factor(direction, levels = c("East", "West", "North"))
print(factor_direction)

```
#4
```{r}
factor_data <- c("East", "West", "North")
frequency_vector <- c(1, 4, 3)
new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```
# 5
```{r}
#a
data <- read.table("import_march.csv", header = TRUE, sep = ",")
```
```{r}
#b
data
```
#6
```{r}
exhaustive_search <- function() {
  # Get input from the user and check if it's a valid number
  number <- suppressWarnings(as.integer(readline(prompt = "Please select a number between 1 and 50: ")))
  if (is.na(number)) {
    print("Invalid input. Please enter a number.")
  } else if (number < 1 || number > 50) {
    print("The number selected is beyond the range of 1 to 50")
  } else if (number == 20) {
    print(TRUE)
  } else {
    print(number)
  }
}
exhaustive_search()
```
#7
```{r}
min_bills <- function(price) {
  bills <- c(1000, 500, 200, 100, 50)
  count <- 0
  for (bill in bills) {
    
    while (price >= bill) {
      price <- price - bill  
      count <- count + 1   
    }
  }
  return(count)
}
snack_price <- 2700
cat("Minimum number of bills needed:", min_bills(snack_price), "\n")
```
#8
```{r}
# a
grades <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)
print(grades)

```
```{r}
# b
for (i in 1:nrow(grades)) {
  avg <- sum(grades[i, 2:5]) / 4
  print(paste(grades$Name[i], "'s average grade this semester is", avg))
}

```
```{r}
# c
for (j in 2:5) {
  avg_test <- mean(grades[,j])
  if (avg_test < 80) {
    print(paste("The", j-1, "test was difficult with an average score of", avg_test))
  }
}
```
```{r}
# d
for (i in 1:nrow(grades)) {
  highest_score <- grades[i, 2]  
  for (j in 3:5) {  
    if (grades[i, j] > highest_score) {
      highest_score <- grades[i, j]
    }
  }
  if (highest_score > 90) {
    print(paste(grades$Name[i], "'s highest grade this semester is", highest_score))
  }
}
```



