---
title: "Rworksheet_Mabalina#3b"
author: "Kristian B. Mabalina"
date: "2024-10-02"
output:
  pdf_document: default
  html_document: default
---
##1
##A
```{r}
SurveyData <- data.frame(
  RespondentID = c(1:20),
  Gender = c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2, 2, 1,2),
  Fathers_Job = c(1, 3, 3, 3, 1, 2, 3, 1, 1, 1, 3, 2, 1, 3, 3, 1, 3, 1, 2, 1),
  HouseholdSize = c(5, 7, 3, 8, 5, 9, 6, 7, 8, 4, 7, 5, 4, 7, 8, 8, 3, 11, 7, 6),
  SchoolAgeSiblings = c(6, 4, 4, 1, 2, 1, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1, 2, 5, 3, 2),
  HomeType = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2)
)

SurveyData
```
##B
```{r}
str(SurveyData)
summary(SurveyData)
```
##C
```{r}
meanSchoolSiblings <- mean(SurveyData$SchoolAgeSiblings)
meanSchoolSiblings
```
##D
```{r}
subset_Respondents <- subset(SurveyData, RespondentID <= 2)
subset_Respondents
```
##E
```{r}
specificData <- SurveyData[c(3,5), c("Gender", "HouseholdSize")]
specificData
```
##F   
```{r}
homeTypes <- SurveyData$HomeType
homeTypes
```
##G
```{r}
maleFarmers <- SurveyData[SurveyData$Gender == 1 & SurveyData$Fathers_Job == 1, ]
maleFarmers
```
##H
```{r}
femaleManySiblings <- SurveyData[SurveyData$Gender == 2 & SurveyData$SchoolAgeSiblings >= 5, ]
femaleManySiblings
```
##2
```{r}
df_empty <- data.frame(
  Ints = integer(), 
  Doubles = double(), 
  Strings = character(), 
  Booleans = logical(), 
  Categories = factor(), 
  stringsAsFactors = FALSE
)
print("Structure of the empty data frame:")
str(df_empty)
```
##3
##A
```{r}
HouseHold <- read.csv("HouseholdData.csv")
HouseHold
```
##B
```{r}
HouseHold$Sex <- factor(HouseHold$Sex, levels = c("Male", "Female"), labels = c(1, 2))
HouseHold$Sex <- as.integer(HouseHold$Sex)
HouseHold
```
##C
```{r}
HouseHold$Types.of.Houses <- factor(HouseHold$Types.of.Houses, 
                                     levels = c("Wood", "Concrete", "Semi-concrete"), 
                                     labels = c(1, 2, 3))
HouseHold$Types.of.Houses <- as.integer(HouseHold$Types.of.Houses)
HouseHold
```
##D
```{r}
HouseHold$Fathers.Occupation <- factor(HouseHold$Fathers.Occupation, 
                                       levels = c(1, 2, 3), 
                                       labels = c("Farmer", "Driver", "Others"))
HouseHold
```
##E
```{r}
femaleDriver <- subset(HouseHold, Sex == 2 & Fathers.Occupation == "Driver")
femaleDriver
```
##F
```{r}
SiblingSchool <- subset(HouseHold, Siblings.at.School >= 5)
SiblingSchool
```

##4
The graph shows that between July 14 and July 21, 2020, there were more negative tweets each day than any other type. Positive tweets were the second highest, and there were the least neutral tweets.

